---
- name: Commmon | Install required system packages.
  apt: 
    name: "{{ item }}"
    state: present
    update-cache: yes
  loop:
    - redis-server

- name: Listen on public interface
  lineinfile: 
    dest: /etc/redis/redis.conf
    regexp: "^bind"
    line: "#bind"
  notify: restart redis

- name: Django | Allow traffic from appservers through firewall
  ufw: 
    rule: allow
    proto: any
    port: 6379
    from_ip: "{{ item }}"
  with_items: "{{ groups['appservers'] }}"
  tags:
    - firewall
    - redis
