---
- name: Nginx | Install required system packages.
  apt: 
    name: "{{ item }}"
    state: present
    update-cache: yes
  loop:
    - build-essential
    - nginx
  tags:
    - packages
    - provision
    - webserver

- name: Nginx | remove default nginx site
  notify: restart nginx
  file: >
    path=/etc/nginx/sites-enabled/default
    state=absent

- name: Nginx | Install nginx configuration file.
  notify: restart nginx
  template: 
    src: load_conf.j2
    dest: /etc/nginx/sites-enabled/default
  tags:
    - config
    - nginx
    - webserver
    - update

- name: Nginx | Allow port 80 through firewall
  ufw: 
    rule: allow
    port: 80
    proto: tcp
  tags:
    - firewall

- name: Servers | Allow port 443 through firewall
  ufw: 
    rule: allow
    port: 443
    proto: tcp
  tags:
    - firewall
